### ISSUE TITLE
Where are the samples stored?

### ISSUE THREAD

**Issue by arbenede** [GeomScale/volume_approximation#18]
I am trying to use vol under Linux to generate uniform random samples from a polytope but I can't figure where the samples are stored. If I run for example

```
./vol -v -f1 cube10.ine -rand -nsample 1000 
```
I get 

```
Verbose mode
Reading input from file...
Input polytope: 10
 20 11 float
1 0 0 0 0 0 0 0 0 0 <= 1
0 1 0 0 0 0 0 0 0 0 <= 1
0 0 1 0 0 0 0 0 0 0 <= 1
0 0 0 1 0 0 0 0 0 0 <= 1
0 0 0 0 1 0 0 0 0 0 <= 1
0 0 0 0 0 1 0 0 0 0 <= 1
0 0 0 0 0 0 1 0 0 0 <= 1
0 0 0 0 0 0 0 1 0 0 <= 1
0 0 0 0 0 0 0 0 1 0 <= 1
0 0 0 0 0 0 0 0 0 1 <= 1
-1 0 0 0 0 0 0 0 0 0 <= 1
0 -1 0 0 0 0 0 0 0 0 <= 1
0 0 -1 0 0 0 0 0 0 0 <= 1
0 0 0 -1 0 0 0 0 0 0 <= 1
0 0 0 0 -1 0 0 0 0 0 <= 1
0 0 0 0 0 -1 0 0 0 0 <= 1
0 0 0 0 0 0 -1 0 0 0 <= 1
0 0 0 0 0 0 0 -1 0 0 <= 1
0 0 0 0 0 0 0 0 -1 0 <= 1
0 0 0 0 0 0 0 0 0 -1 <= 1
Generate random points only
Inner ball time: 0.000803
Inner ball center is: 
0 0 0 0 0 0 0 0 0 0 
radius is: 1
Sampling time: 0.001194
```

**Comment by TolisChal** [comment]
Hello,

In C++ interface there is not a structure or a txt that the points are
stored into. I think the easiest way is to print the points on terminal.
You can add in /test/vol.cpp at line 456 (before return 0;) the following:

for (typename std::list<Point>::iterator pit = randPoints.begin();
pit!=randPoints.end(); ++pit) (*pit).print();

You can also use the CRAN R package volesti (
https://cran.r-project.org/web/packages/volesti/index.html ). You can
install it by running

R> install.packages("volesti")

The function to sample points is `sample_points()`. You can see the
documentation in
https://cran.r-project.org/web/packages/volesti/volesti.pdf

**Comment by arbenede** [comment]
Thank you Tolis, that's exactly what I was looking for.
