### ISSUE TITLE
How to compute the intersection of V-polytopes

### ISSUE THREAD

**Issue by Svankah** [GeomScale/volume_approximation#51]
Is there a function that does the intersection of V-polytopes, like it is stated for the class IntVP?

**Comment by TolisChal** [comment]
You will need the R version of package `volesti` for the intersection of two V-polytopes.
You should use the function `volume`. Store the vertices of the polytopes, row-wise, in two matrices V1, V2. Then define the polytope as below,

`> P = IntVP$new(V1 = V1, V2 = V2) `

**Comment by Svankah** [comment]
Where should I use the function volume? Since I defined P doing this

> P = IntVP$new(V1 = V1, V2 = V2)
Then
> P
C++ object <0x7f92030d6020> of class 'IntVP' <0x7f91fe85c7e0>



How to obtain the vertices of the intersection of the 2 polytopes?


Thank you.


Le 23 décembre 2019 à 9:41, Tolis Chalkis <notifications@github.com> a écrit :



You will need the R version of package volesti for the intersection of two V-polytopes.
You should use the function volume. Store the vertices of the polytopes, row-wise, in two matrices V1, V2. Then define the polytope as below,

**Comment by TolisChal** [comment]
`volesti` does not compute the vertices of such a polytope. You can compute (approximately) the volume or sample from it.

**Comment by Svankah** [comment]
Thank you !

**Comment by TolisChal** [comment]
Thank you for your interest. I close this issue.

**Comment by vissarion** [comment]
@Svankah the function `intersectn` from  R package `geometry` should do what you want. See https://cran.r-project.org/web/packages/geometry/geometry.pdf
