### ISSUE TITLE
Error in the .ext file representation

### ISSUE THREAD

**Issue by Hepic** [GeomScale/volume_approximation#67]
**Describe the bug**
In the **Polytope input** section of the README, the representation of a V-polytope in a .ext file
contains the line `m d numbertype`, while it should be `m d+1 numbertype`.

**To Reproduce**
1. Go to the _test_ folder.
2. Compile with cmake and make.
3. Execute the command `./generate -simplex -v -d 2`.
4. Open the file _simplex_2.ext_. The corresponding line has the value three (d+1) instead of two (d).

**Comment by vissarion** [comment]
Thanks for finding the typo!
