### ISSUE TITLE
Sample Points cannot use InnerPoint parameter

### ISSUE THREAD

**Issue by jasonNikolaou** [GeomScale/volume_approximation#72]
**Describe the bug**
When i use the sample_points function and pass the paramater InnerPoint i get the following
error:
Error in sample_points(P, N = 1, distribution = "gaussian", InnerPoint = point) :
std::bad_alloc

**To Reproduce**
Code:
```
library(volesti)
A = rbind(c(1,0), c(0,1),
c(-1,0), c(0,-1))
b = c(1,1,0,0)
P = Hpolytope$new(A, b)
point = c(0.2, 0.2)
x = sample_points(P, distribution="gaussian", InnerPoint=point)
```

**Environment**
Ubuntu 18.04 LTS
Rstudio, compiler version: 3.4.4
volesti version: 1.0.3

**Comment by Ritik2604** [comment]
std::bad_alloc is the type of the object thrown as exceptions by the allocation functions to report failure to allocate storage.

**Comment by vissarion** [comment]
Are you still getting a `std::bad_alloc` in version > `1.1.0`?

The following snipset does not throw a `std::bad_alloc` but does not generate correct points either. It generates multiple copies of the initial point. If you remove the initial point parameter, it seems to work fine. Thus it seems there is a (new) bug while using the initial point parameter.

```
library(volesti)
A = rbind(c(1,0), c(0,1),
          c(-1,0), c(0,-1))
b = c(1,1,0,0)
P = Hpolytope$new(A, b)
point = c(0.2, 0.2)
x = sample_points(P, 100, random_walk = list("starting_point" = point))
```

*Environment*
Ubuntu 18.04.4 LTS
Rstudio Version 1.2.1578
volesti version 1.1.1

**Comment by vissarion** [comment]
I am closing this issue, @jasonNikolaou if you are still facing some related issue feel free to open it again.
